{
   "Version": "2012-10-17",
   "Statement": [
       {
           "Sid": "AWSAdminAccess",
           "Effect": "Allow",
           "Action": "*",
           "Resource": "*"
       },
       {
           "Effect": "Allow",
           "Action": [
               "iam:PassRole",
               "iam:ListInstanceProfiles"
           ],
           "Resource": "*"
       },
       {
           "Sid": "IAMAccess",
           "Effect": "Deny",
           "Action": [
               "iam:CreateUser",
               "iam:UpdateUser",
               "iam:DeleteUser",
               "iam:AttachUserPolicy",
               "iam:DetachUserPolicy",
               "iam:DeleteUserPolicy",
               "iam:AddUserToGroup",
               "iam:RemoveUserFromGroup",
               "iam:DeleteRole",
               "iam:DeleteRolePolicy",
               "iam:CreateGroup",
               "iam:UpdateGroup",
               "iam:DeleteGroup",
               "iam:DetachGroupPolicy",
               "iam:DeleteGroupPolicy",
               "iam:CreateSAMLProvider",
               "iam:UpdateSAMLProvider",
               "iam:DeleteSAMLProvider",
               "iam:CreateAccountAlias",
               "iam:DeleteAccountAlias",
               "iam:ChangePassword",
               "iam:UpdateAccountPasswordPolicy",
               "iam:DeleteAccountPasswordPolicy",
               "iam:CreateLoginProfile",
               "iam:DeleteLoginProfile",
               "iam:DeleteInstanceProfile",
               "iam:DeleteServerCertificate",
               "iam:DeleteSigningCertificate",
               "iam:UpdateAccessKey",
               "iam:DeleteAccessKey",
               "iam:UpdateSSHPublicKey",
               "iam:DeleteSSHPublicKey",
               "iam:DeleteServiceSpecificCredential"
           ],
           "Resource": "*"
       },
       {
          "Sid": "NetworkAccess",
           "Effect": "Deny",
           "Action": [
               "ec2:CreateVpc",
               "ec2:CreateDefaultVpc",
               "ec2:ModifyVpcAttribute",
               "ec2:DeleteVpc",
               "ec2:CreateSubnet",
               "ec2:ModifySubnetAttribute",
               "ec2:DeleteSubnet",
               "ec2:CreateRouteTable",
               "ec2:DeleteRouteTable",
               "ec2:DisassociateRouteTable",
               "ec2:DisassociateVpcCidrBlock",
               "ec2:AssociateVpcCidrBlock",
               "ec2:DisassociateSubnetCidrBlock",
               "ec2:AssociateSubnetCidrBlock",
               "ec2:CreateInternetGateway",
               "ec2:DeleteInternetGateway",
               "ec2:AttachInternetGateway",
               "ec2:DetachInternetGateway",
               "ec2:EnableVpcClassicLink",
               "ec2:DisableVpcClassicLink",
               "ec2:EnableVpcClassicLinkDnsSupport",
               "ec2:DisableVpcClassicLinkDnsSupport",
               "ec2:CreateVpnGateway",
               "ec2:DeleteVpnGateway",
               "ec2:CreateCustomerGateway",
               "ec2:DeleteCustomerGateway",
               "ec2:CreateVpnConnection",
               "ec2:CreateVpnConnectionRoute",
               "ec2:DeleteVpnConnection",
               "ec2:DeleteVpnConnectionRoute",
               "ec2:CreateVpcEndpoint",
               "ec2:DeleteVpcEndpoints",
               "ec2:RejectVpcEndpointConnections",
               "ec2:CreateVpcEndpointServiceConfiguration",
               "ec2:ModifyVpcEndpointServiceConfiguration",
               "ec2:DeleteVpcEndpointServiceConfigurations",
               "ec2:CreateVpcEndpointConnectionNotification",
               "ec2:ModifyVpcEndpointConnectionNotification",
               "ec2:DeleteVpcEndpointConnectionNotifications",
               "ec2:CreateVpcPeeringConnection",
               "ec2:RejectVpcPeeringConnection"
           ],
           "Resource": "*"
       }
   ]
}
